### PR TITLE
16.2 bugfixes

### LINKED ISSUE #1392: On First Login Names And Paswords aren't set Redis
Typically on a first login the system asks for user names and/or passwords for setting up systems. On the redis system that doesn't happen.

### LINKED ISSUE #1533: Redis - Confconsole password checking function not working
@SupaYoshi [reported](https://github.com/turnkeylinux/tracker/issues/1392#issuecomment-723590167) that the Redis Password checking Confconsole script is broken:

confconsole_1
confconsole_2

I've had a look and confirmed the issue (not sure how I missed this previously?!)

I've made some modifications and have renamed the script (the script name affects how it displays in Confconsole). TO manually update yourself:

```
PATH=usr/lib/confconsole/plugins.d
rm /$PATH/get_pass.py
NEW_SCRIPT=$PATH/get_redis_pass.py
wget https://raw.githubusercontent.com/JedMeister/redis/16.2-bugfixes/overlay/$NEW_SCRIPT -O /$NEW_SCRIPT
```

Note that if the wget line fails, then the script is most likely been merged into the TurnKey apps Redis repo and my fork has been removed. I'll try to remember to update this URL when I do that. But if I forget, please post and I will update the URL.

### PR DESCRIPTION
**Pull request by JedMeister**
Pull request to resolve some Redis bugs.

Closes https://github.com/turnkeylinux/tracker/issues/1533
Closes https://github.com/turnkeylinux/tracker/issues/1392

### CODE REVIEW

**Comment by JedMeister** [comment]
Note the force pushes were just to tidy up the commit messages...

**Review by OnGle — APPROVED** [review]
Looks good to me although I'd like to note that the bind-ip will probably want more options eventually. There is at least 1 more option that may be wanted for it beyond localhost and internet wide: local-ip (of your local subnet ip) for locally, but not internet wide serving on a server connected TO the wider internet. Also a user may want a specific local ip for a specific interface if they're connected to multiple subnets.

This is probably good for the moment but worth noting eitherway.

**Comment by JedMeister** [comment]
@OnGle - good note. I've opened an issue regarding your feedback: https://github.com/turnkeylinux/tracker/issues/1537

Although I have just noticed that I haven't bumped the changelog. Doh! I'll do that now, then merge this PR.

**Comment by masoudei** [comment]
When this error will be fixed? we are waiting for that .. and can we use this LXC for our customers to connect to it and use Redis  with multiple DBs or multiple Users ( ACL ) ?

I mean every customer only see its only DB and we have to make users yes ?

**Comment by JedMeister** [comment]
@masoudei - Apologies that I missed your post. And also apologies that this hasn't been rebuilt yet.

I'm currently in the process of going through appliances and updating them all. I will try to squeeze this one into the next batch. If it makes it, hopefully it should be ready mid next week. If not, then within the next few weeks.

If that's too far away for you, you could easily build this yourself.I'm more than happy to assist you to do that.

**Pull request merged**
